name: pages

on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'arlac77/svelte-guard-history-router'
          path: build/components/svelte-guard-history-router
          clean: false
      - uses: actions/setup-node@v1
        with:
          node-version: 14.5.0
      - run: |
          cd build/components/svelte-guard-history-router
          npm install
          npx rollup -c example/rollup.config.mjs
      - uses: actions/checkout@v2
        with:
          repository: 'arlac77/svelte-common'
          path: build/components/svelte-common
          clean: false
      - uses: actions/setup-node@v1
        with:
          node-version: 14.5.0
      - run: |
          cd build/components/svelte-common
          npm install
          npx rollup -c example/rollup.config.mjs
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: master
          build_dir: build
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          