name: pages

on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'arlac77/svelte-guard-history-router'
      - uses: actions/setup-node@v1
        with:
          node-version: 14.5.0
      - run: |
          npm install
          npx rollup -c example/rollup.config.mjs
          mkdir -p build/components/svelte-guard-history-router/example
          cp -R example/public/* build/components/svelte-guard-history-router/example
      -
        name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: master
          build_dir: build
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          