name: pages

on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: arlac77/svelte-repository-provider
          path: build/svelte-repository-provider
          clean: false
      - uses: actions/checkout@v2
        with:
          repository: arlac77/svelte-log-view
          path: build/svelte-log-view
          clean: false
      - uses: actions/checkout@v2
        with:
          repository: arlac77/svelte-session-manager
          path: build/svelte-session-manager
          clean: false
      - uses: actions/checkout@v2
        with:
          repository: arlac77/svelte-guard-history-router
          path: build/svelte-guard-history-router
          clean: false
      - uses: actions/checkout@v2
        with:
          repository: arlac77/svelte-common
          path: build/svelte-common
          clean: false
      - uses: actions/checkout@v2
        with:
          repository: arlac77/svelte-websocket-store
          path: build/svelte-websocket-store
          clean: false
      - uses: actions/setup-node@v1
        with:
          node-version: 14.19.1
      - run: |
          COMPONENTS="svelte-repository-provider svelte-websocket-store svelte-log-view svelte-session-manager svelte-common svelte-guard-history-router"
          for c in $COMPONENTS
          do
            echo '****** ' $c ' ******'
            (cd build/$c;npm install;npx rollup -c tests/app/rollup.config.mjs)
            mkdir -p build/components/$c/tests/app
            cp -R build/$c/tests/app/public/* build/components/$c/tests/app
            rm -rf build/$c
          done
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: master
          build_dir: build
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          