name: pages

on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'arlac77/svelte-guard-history-router'
          path: build/svelte-guard-history-router
          clean: false
      - uses: actions/checkout@v2
        with:
          repository: 'arlac77/svelte-common'
          path: build/svelte-common
          clean: false
      - uses: actions/setup-node@v1
        with:
          node-version: 14.5.0
      - run: |
          COMPONENTS="svelte-guard-history-router svelte-common"
          for c in $COMPONENTS
          do
            (cd build/$c;npm install;npx rollup -c example/rollup.config.mjs)
            mkdir -p build/components/$c
            cp -R build/$c/example/public build/components/$c
            rm -rf build/$c
          done
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: master
          build_dir: build
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          